language: python

# python version
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE storemanagertest;' -U postgres

# command to run tests
script:
  - coverage run --source=app.api -m pytest app/tests -v -W error::UserWarning && coverage report

# Post coverage results to coverage.io
after_success:
  - coveralls